# Generated by Django 4.0.5 on 2022-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JardinWeb', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(default=9999, primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=100, verbose_name='nombre producto'),
        ),
    ]
