# Generated by Django 4.0.5 on 2022-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JardinWeb', '0003_producto_idproducto_alter_producto_nombreproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=1000, verbose_name='Marca'),
        ),
    ]
