# Generated by Django 4.0.1 on 2022-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JardinWeb', '0005_alter_producto_descripcion_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id producto'),
        ),
    ]
