# Generated by Django 4.0.5 on 2022-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JardinWeb', '0006_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(null=True),
        ),
    ]
